### PR TITLE
Resolves #37

### LINKED ISSUE #37: No way to clear the Endpoint registry
There seems to be no way to clear the Endpoint registry. This means if you're testing with lots of test cases, there is no way to reset the registry.

### PR DESCRIPTION
**Pull request by davidyell**
Updated the Registry with a way to clear and remove. Also added a test class for the new methods and existing ones.

### CODE REVIEW

**Comment by davidyell** [comment]
Blocked by #39 as this pull request doesn't have the updated PHPUnit for the tests to pass.

**Comment by ADmad** [comment]
#39 has been merged. Please rebase.

**Comment by davidyell** [comment]
Finally got around to merging these. Hopefully Travis approves.

**Comment by davidyell** [comment]
Thanks @ADmad

**Pull request merged**
