### PR TITLE
Use a strict comparison when checking the primary key

### PR DESCRIPTION
**Pull request by Marlinc**
This resolves issue #10

### CODE REVIEW

**Comment by ADmad** [comment]
Tests failing.

**Comment by Marlinc** [comment]
That's cause of the issue related to the BC break in CakePHP. I'm working on a PR to fix that in the core. Its not related to this change.

**Comment by Marlinc** [comment]
I've opened cakephp/cakephp#8211 which should resolve some of the issues.

**Comment by Marlinc** [comment]
Opened a new PR for this: #14

**Pull request closed without merging**
