### PR TITLE
Resolves #2

### LINKED ISSUE #2: Missing exception
It seems that this class is missing from the repo.

`Muffin\Webservice\Exception\UnimplementedWebserviceMethodException`

### PR DESCRIPTION
**Pull request by davidyell**
Added missing exception class

### CODE REVIEW

**Comment by ADmad** [comment]
Can you please add test which triggers this exception.

**Comment by davidyell** [comment]
I'd love to, but there aren't any tests to go on. I'd feel happier extending existing tests to ensure that the code formatting was similar.

**Comment by ADmad** [comment]
Give it a shot and ask for pointers if you get stuck. In general check core for how exception throwing from a method is tested.

**Comment by steefaan** [comment]
Maybe you should already merge this and do the test cases with a separate PR. Currently you get a `Fatal Error` because the class is missing. This would solve at least this bad issue.

**Comment by davidyell** [comment]
It would be handy, as I've just been given a huge project at work, so will not have much time to work on this. I can try and find some time in the evenings, but it's a long shot.

**Comment by jadb** [comment]
I agree @steefaan but giving a hand to @davidyell wouldn't have hurt ;)

**Pull request merged**
