### PR TITLE
Plugin loading

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by ADmad** [comment]
@davidyell Please try this out and let me know if things work as expected.

**Comment by davidyell** [comment]
I've followed through the readme instructions [with a fresh application](https://github.com/davidyell/Example-MuffinWebservice), and I hit a few issues.

## Default connection configuration

```
Missing Datasource Configuration
Cake\Datasource\Exception\MissingDatasourceConfigException

⟩ Cake\Datasource\ConnectionManager::get
ROOT/vendor/muffin/webservice/src/Model/EndpointLocator.php, line 99
```

I solved this problem, by defining the `Endpoint::defaultConnectionName()` method in my endpoint class, and returning `'default'`. As you'll see below, this was not correct.

## Getting the webservice from the connection

```
Call to undefined method Cake\Database\Connection::getWebservice()

⟩ Muffin\Webservice\Model\Endpoint->getWebservice
ROOT/vendor/muffin/webservice/src/Model/Endpoint.php, line 998
```

I solved this problem by [defining my Datasource configuration](https://github.com/davidyell/Example-MuffinWebservice/blob/master/config/app.default.php#L312-L322) in my `app.php` file.

```php
'Datasources' => [
    'yesnowtf' => [
        'className' => \Muffin\Webservice\Connection::class,
        'driver' => \App\Webservice\Driver\Answers::class,
        'host' => 'yesno.wtf'
    ]
]
```

Then updating my Endpoint classes `defaultConnectionName()` method to return `yesnowtf`.

## Single result

I found a slight issue when trying to load a single resource. There is `Webservice::_transformResource()` which takes an Endpoint instance, and an array result.

However the `Webservice::getEndpoint()` method doesn't return an instance, but instead a string. So I had to sidestep this in my Webservice, by passing a new instance.

```php
$resource = $this->_transformResource(new AnswersEndpoint(), $resultArray);
```

I'm unsure of the originally intended functionality, and the docblocks are not very descriptive. We'd need to ask @marlinc. We've also yet to implement any type hinting here to help developers understand what the code is expecting.

Additionally, you have to pass the subsequent `ResultSet` class an array, regardless of the number of results. So I had to [sidestep that by wrapping my resource in an array](https://github.com/davidyell/Example-MuffinWebservice/blob/master/src/Webservice/AnswersWebservice.php#L35).

```php
return new ResultSet([$resource], 1);
```

The upshot of all this is that [I've had to call `first()` on the query in my controller](https://github.com/davidyell/Example-MuffinWebservice/blob/master/src/Controller/AnswersController.php#L24), in order to set a single item to the view.

```php
$answer = $this->Answers->find()
    ->execute();

$this->set('answer', $answer->first());
```

## Overall
Everything is working fine, but we do lack a little detail in the documentation, which could be hard for users to work out by reading the code.

**Comment by ADmad** [comment]
> Getting the webservice from the connection

Yeah the plugin conventionally looks for a datasource config with name same as underscored version of webservice class name or driver class name (I don't exactly remember which). Explicitly setting connection name is required only if you don't have a datasource config matching that name. So the docs needs to be updated to mention that.

> So I had to sidestep this in my Webservice, by passing a new instance.

Where exactly did you do this? Checking one of my old implementations I have done `$resource = $this->_transformResource($query->endpoint(), $record);` in overridden `Webservice::_executeReadQuery()` method.

> Additionally, you have to pass the subsequent ResultSet class an array

Yes `ResultSet` is always meant to represent multiple records, so in cases where your external webservice returns only one record you have to `return new ResultSet([$resource], 1);`. As you have found later this is necessary so that `->first()` works the same way as it does for results sets from tables queries.

**Comment by davidyell** [comment]
I think I have mistakenly removed the `$query->endpoint()` call, and replaced it with a call to a new instance.

**Comment by davidyell** [comment]
@ADmad What are your thoughts on a `/docs` folder with stuff in? Do you think we have sufficient complexity to require a more verbose documentation implementation?

**Comment by ADmad** [comment]
If you are willing to put in the effort to write more verbose docs then go for it. Using `/docs` would be fine.

**Comment by ADmad** [comment]
@
 You can make a follow up PR for docs :)

**Pull request merged**
